### ISSUE TITLE
Create PURL services documentation

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#249]
We should create and publish on RTD a comprehensive installation and usage documentation for the various PURL-based services of PurlDB. This should be backed by a publicly accessible demo system

- [x] https://github.com/nexB/purldb/issues/445 with PR in https://github.com/nexB/purldb/pull/456
- [x] https://github.com/nexB/purldb/issues/446 merged with https://github.com/nexB/purldb/pull/450
- [x] https://github.com/nexB/purldb/issues/448
- [x] https://github.com/nexB/purldb/issues/457

**Comment by pombredanne** [comment]
We would need some doc for the purlcli and some doc for each of the endpoints

**Comment by pombredanne** [comment]
@johnmhoran @AyanSinhaMahapatra is this something you guys could get started?
Overall we would need some doc in the same style and structure as ScanCode.io?

**Comment by johnmhoran** [comment]
@pombredanne I just saw this.  Yes, I'd be happy to work with @AyanSinhaMahapatra on this -- we can start by finding a time to discuss general structure and content and see how the ScanCode.io RTD informs our work.  I'll also need to learn what the various endpoints do and how we use them.

Unless you suggest otherwise, I would like to get a bit more of my PURL CLI work out of the way first since I'm still wrestling with the `urls` command, have not yet fully changed the four existing commands to the SCTK-like data structure, and have more commands to add (`scan` and `git` -- and perhaps others?).

**Comment by pombredanne** [comment]
Some status update:
- We created and published the API definitions documentation see code https://github.com/nexB/purldb/commit/cfc1c9676f9bb6a893bbb3ff573c726033e0e404
- This is deployed on public.purldb.io at `/api/docs` for the docs and the schema is at `/api/`. See the live API doc https://private.purldb.io/api/docs/ and schema https://private.purldb.io/api/schema

- We also updated the built-in documentation of end points accordingly

**Comment by johnmhoran** [comment]
@pombredanne @AyanSinhaMahapatra As noted a bit earlier in [purldb PR 436](https://github.com/nexB/purldb/pull/436), I've added details to the existing purldb-toolkit RTD page re the use of the four current PURLCLI tools, with a mix of command and output examples and several related notes.  The .rst is here:

https://github.com/nexB/purldb/blob/f49eff87ae9a4226584096498836de7d5015f6a2/purldb-toolkit/README.rst

The initial description above for this issue also says `This should be backed by a publicly accessible demo system`.  What is this?  Any examples or articles or a design doc?

**Comment by pombredanne** [comment]
All done, now published at https://aboutcode.readthedocs.io/projects/PURLdb/en/latest/index.html
